---
- name: configure the Windows Server
  hosts: all

  tasks:
  - name: install common packages
    win_chocolatey:
      name: '{{item}}'
      state: present
    with_items:
    - sysinternals
    - notepadplusplus
    - googlechrome
    - git
